In [14]:
#陣列, 向量 (一個維度的陣列 1D)運算

#a = [a1, a2, a3] #向量
#s = 5 #純量 (Scalar)
#c = a + s = [a1+s, a2+s, a3+s]

import numpy as np
a = np.array([1, 2, 3])
print('a=' + str(a))
s = 5
print('s=' + str(s))
b = a + s
print('a+s=', str(b)) #向量的加法運算

#3分鐘練習, 6:53

#你自己試試減法運算 b = a - s , 二分鐘
b = a - s
print('a-s=' + str(b))

#你自己試試乘法運算 b = a * s, 二分鐘
b = a * s
print('a*s=' + str(b))

a = np.array([1, 2, 3])
c = np.array([4, 5, 6])
d = a + c
print(str(d))

# a = [1, 2, 3] list; np.array([1, 2, 3])
# 向量與向量之間的運算
d = a * c
print(str(d))

#3分鐘練習, 7:05

a=[1 2 3]
s=5
a+s= [6 7 8]
a-s=[-4 -3 -2]
a*s=[ 5 10 15]
[5 7 9]
[ 4 10 18]


In [17]:
#向量 點積 運算 - Dot Product
a = np.array([1, 2, 3])
print('a=' + str(a))
s = np.array([4, 5, 6])
print('s='+str(s))
b = a.dot(s)
print('a.dot(s)=' + str(b))  # 1*4, 2*5, 3*6
# 3 分鐘練習, 7: 12

a=[1 2 3]
s=[4 5 6]
a.dot(s)=32


In [20]:
#向量 與 布林值 遮罩 (mask)
a = np.array([14, 8, 10, 11, 6, 3, 18, 13, 12, 9])
print('a='+str(a))
mask = (a % 3 == 0) #建立布林值陣列
print('mask=' + str(mask))
b = a[mask] #使用布林值陣列取出值
print('b='+str(b))

#3 分鐘練習, 7:20

a=[14  8 10 11  6  3 18 13 12  9]
mask=[False False False False  True  True  True False  True  True]
b=[ 6  3 18 12  9]


In [27]:
#陣列的函式
# ravel(), flatten() -> 把陣列拉平 -> 一個維度
a = np.array([[1, 2, 3], [4, 5, 6]])
b = a.ravel()
print(str(b))

# reshape -> 改變陣列的形狀
c = np.reshape(b, (2, 3))
print(str(c))

#第一節休息10分鐘, 7:40 繼續

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [30]:
# Pandas -> Python and data analysis
  # 索引陣列結構 Series, DataFrame 物件
  # 多層次的階層索引
  # Agrregating, Transform
  # 檔案讀取, 轉換,純存

import pandas as pd
# 自訂索引
fruits = ['蘋果', '橘子', '梨子', '櫻桃', '蓮霧', '釋迦']
s = pd.Series([12, 29, 72, 4, 8, 10], index=fruits)
print(s)

#3分鐘練習, 7:53

蘋果    12
橘子    29
梨子    72
櫻桃     4
蓮霧     8
釋迦    10
dtype: int64


In [33]:
print('橘子=', s['橘子'])
print(s[['梨子', '蓮霧', '釋迦']])
print((s+2)*3)

#3分鐘練習, 7:59

橘子= 29
梨子    72
蓮霧     8
釋迦    10
dtype: int64
蘋果     42
橘子     93
梨子    222
櫻桃     18
蓮霧     30
釋迦     36
dtype: int64


In [41]:
# DataFrame (Excel, Table)
# 資料來源: excel, csv, 資料庫, 字典 dict

dists = {'name':['中正區', '板橋區', '桃園區', '北屯區',
                 '安南區', '三民區', '大安區', '永和區',
                 '八德區', '前鎮區', '鳳山區',
                 '信義區', '新店區'],
         'population': [159598, 551452, 44287, 275207,
                        192327, 343203, 309835, 222531,
                        198473, 189623, 359125,
                        225561, 302070],
         'city': ['台北市', '新北市', '桃園市', '台中市',
                  '台南市', '高雄市', '台北市', '新北市',
                  '桃園市', '高雄市', '高雄市',
                  '台北市', '新北市'] }

ordinals = ['第一選區', '第二選區', '第三選區', '第四選區', '第五選區', '第六選區', '第七選區', '第八選區', '第九選區', '第十選區', '第十一選區', '第十二選區', '第十三選區']

#請完成上面 dictionary 資料, 至 8:14
df = pd.DataFrame(dists, columns = ['name', 'population', 'city'], index = ordinals)
print(df)

# 3 分鐘練習, 8:26

      name  population city
第一選區   中正區      159598  台北市
第二選區   板橋區      551452  新北市
第三選區   桃園區       44287  桃園市
第四選區   北屯區      275207  台中市
第五選區   安南區      192327  台南市
第六選區   三民區      343203  高雄市
第七選區   大安區      309835  台北市
第八選區   永和區      222531  新北市
第九選區   八德區      198473  桃園市
第十選區   前鎮區      189623  高雄市
第十一選區  鳳山區      359125  高雄市
第十二選區  信義區      225561  台北市
第十三選區  新店區      302070  新北市


In [39]:
df.to_html('ex01.html')

In [42]:
df2 = pd.DataFrame(dists, columns= ['name', 'population'], index = dists['city'])
print(df2)
#3分鐘練習, 8:31

    name  population
台北市  中正區      159598
新北市  板橋區      551452
桃園市  桃園區       44287
台中市  北屯區      275207
台南市  安南區      192327
高雄市  三民區      343203
台北市  大安區      309835
新北市  永和區      222531
桃園市  八德區      198473
高雄市  前鎮區      189623
高雄市  鳳山區      359125
台北市  信義區      225561
新北市  新店區      302070


In [45]:
#第二節課休息10分鐘, 8:42 繼續
# to_csv(), to_json, to_html, to_excel, to_sql
# read_csv(), read_json, read_html, read_sql

df.to_csv('dists2.csv', index=False, encoding='utf8')

In [46]:
df.to_json('dists.json')
#3 分鐘練習, 8:50

In [52]:
df.head(3)
df.tail(2)
len(df)
df.shape

(13, 3)

In [ ]:
#使用 iterrows() 函數走訪 DataFrame 物件
for index, row in df.iterrows():
  print(index, row['city'], row['name'], row['population'])
  print('--------------------------------------------------')

# 3 分鐘練習, 9:00

In [ ]:
# DataFrame 資料的過濾和排序
print(df.population > 350000)
print(df['city'].isin(['台北市', '高雄市']))
#3分鐘練習, 9:06

In [ ]:
# 資料的新增與刪除
df
df.loc['第一選區'] = ['士林區', 288340, '台北市']
print(df.tail(3))

s = pd.Series({'city':'新北市', 'name':'中和區', 'population':413291})
df3 = df.append(s, ignore_index=True)
df3


In [ ]:
df3.drop([13])
#3分鐘練習, 9:17

In [65]:
# 分群 (Grouping), 樞紐分析
df = pd.DataFrame({'名稱': ['客戶A', '客戶B', '客戶A', '客戶B', '客戶A', '客戶B', '客戶A', '客戶A'],
                   '編號':['訂單1', '訂單1', '訂單2', '訂單3', '訂單2', '訂單1', '訂單1', '訂單3'],
                   '數量': np.random.randint(1,5, size=8),
                   '售價': np.random.randint(150, 500, size=8)
                   })
df
#3分鐘時間建立資料, 9: 27

名稱   編號  數量   售價
0  客戶A  訂單1   4  194
1  客戶B  訂單1   2  444
2  客戶A  訂單2   2  397
3  客戶B  訂單3   3  315
4  客戶A  訂單2   2  468
5  客戶B  訂單1   4  194
6  客戶A  訂單1   2  402
7  客戶A  訂單3   1  197

In [67]:
print(df.groupby('名稱').sum())
print('-----------------------')
df.groupby(['名稱', '編號']).sum()

     數量    售價
名稱           
客戶A  11  1658
客戶B   9   953
-----------------------


<ipython-input-67-67e2f8af4684>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  print(df.groupby('名稱').sum())


數量   售價
名稱  編號          
客戶A 訂單1   6  596
    訂單2   4  865
    訂單3   1  197
客戶B 訂單1   6  638
    訂單3   3  315

In [69]:
#樞紐分析 pivot_table
pivot_a = df.pivot_table(index='名稱', columns='編號', values='售價')
pivot_b = df.pivot_table(index='名稱', columns='編號', values='數量')
print(pivot_a)
print('---------------------')
print(pivot_b)

編號     訂單1    訂單2    訂單3
名稱                      
客戶A  298.0  432.5  197.0
客戶B  319.0    NaN  315.0
---------------------
編號   訂單1  訂單2  訂單3
名稱                
客戶A  3.0  2.0  1.0
客戶B  3.0  NaN  3.0
